<pre>--- Summary ---
Tests passed: 2 out of 4

--- Details ---
Test #0: failed 
Test case description: ML4T-220
Traceback:
  File "grade_strategy_learner.py", line 231, in test_strategy
    raise IncorrectOutput, "Test failed on one or more output criteria.\n  Inputs:\n{}\n  Failures:\n{}".format(inputs_str, "\n".join(msgs))
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'ed': datetime.datetime(2009, 12, 31, 0, 0), 'symbol': 'ML4T-220', 'sv': 100000, 'sd': datetime.datetime(2008, 1, 1, 0, 0)}
    outsample_args: {'ed': datetime.datetime(2011, 12, 31, 0, 0), 'symbol': 'ML4T-220', 'sv': 100000, 'sd': datetime.datetime(2010, 1, 1, 0, 0)}
    benchmark_type: clean
    benchmark: 1.0
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-0.30440164) did not beat benchmark (1.0)
  out-sample return (-0.43479679) did not beat benchmark (1.0)

Test #1: passed 
Test #2: failed 
Test case description: SINE_FAST_NOISE
Traceback:
  File "grade_strategy_learner.py", line 231, in test_strategy
    raise IncorrectOutput, "Test failed on one or more output criteria.\n  Inputs:\n{}\n  Failures:\n{}".format(inputs_str, "\n".join(msgs))
IncorrectOutput: Test failed on one or more output criteria.
  Inputs:
    insample_args: {'ed': datetime.datetime(2009, 12, 31, 0, 0), 'symbol': 'SINE_FAST_NOISE', 'sv': 100000, 'sd': datetime.datetime(2008, 1, 1, 0, 0)}
    outsample_args: {'ed': datetime.datetime(2011, 12, 31, 0, 0), 'symbol': 'SINE_FAST_NOISE', 'sv': 100000, 'sd': datetime.datetime(2010, 1, 1, 0, 0)}
    benchmark_type: noisy
    benchmark: 2.0
    train_time: 25
    test_time: 5
    max_time: 60
    seed: 1481090000

  Failures:
  in-sample return (-1.16854228908) did not beat benchmark (2.0)

Test #3: passed 
</pre>
